Expm.Package.new(name: "cowboy", description: "Small, fast, modular HTTP server",
                 version: "0.6.1", keywords: ["http","server","erlang"],
                 licenses: [[name: "BSD", file: "LICENSE"]],
                 contributors: [
                    [name: "Ali Sabil", email: "ali.sabil@tillitech.com"],
                    [name: "alisdair sullivan", email: "alisdairsullivan@yahoo.ca"],                
                    [name: "Andrew Thompson", email: "andrew@hijacked.us"],
                    [name: "Anthony Ramine", email: "n.oxyde@gmail.com"],
                    [name: "Bob Ippolito", email: "bob@redivi.com"],
                    [name: "Boris Faure", email: "boris@fau.re"],
                    [name: "David Kelly", email: "dkelly@ngmoco.com"],
                    [name: "DeadZen", email: "deadzen@deadzen.com"],
                    [name: "Dmitry Groshev", email: "lambdadmitry@gmail.com"],
                    [name: "Hans Ulrich Niedermann", email: "hun@n-dimensional.de"],
                    [name: "Hunter Morris", email: "hunter.morris@smarkets.com"],
                    [name: "Jesper Louis Andersen", email: "jesper.louis.andersen@gmail.com"],
                    [name: "Josh Marchán", email: "josh@siftlogic.com"],
                    [name: "Josh Toft", email: "joshtoft@gmail.com"],
                    [name: "Magnus Klaar", email: "magnus.klaar@gmail.com"],
                    [name: "Mathieu Lecarme", email: "mathieu@garambrogne.net"],
                    [name: "Max Lapshin", email: "max@maxidoors.ru"],
                    [name: "Michiel Hakvoort", email: "michiel@hakvoort.it"],
                    [name: "Ori Bar", email: "ori.bar@nivertech.com"],
                    [name: "Paul Oliver", email: "puzza007@gmail.com"],
                    [name: "Roberto Ostinelli", email: "roberto@ostinelli.net"],
                    [name: "Seven Du", email: "dujinfang@gmail.com"],
                    [name: "Steven Gravell", email: "steve.gravell@smarkets.com"],
                    [name: "Tim Dysinger", email: "tim@dysinger.net"],
                    [name: "Tom Burdick", email: "thomas.burdick@gmail.com"],
                    [name: "Yurii Rashkovskii", email: "yrashk@gmail.com"],
                 ],
                 maintainers: [[name: "Loïc Hoguin", 
                                email: "essen@ninenines.eu"]],
                 repositories: [[github: "extend/cowboy", tag: "0.6.1"]])
    
